import type { Metadata } from "next";
import { pretendard } from "@/lib/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.className} antialiased`}>
      <body className="bg-white text-black min-w-[360px] max-w-[480px] mx-auto p-5">
        {children}
      </body>
    </html>
  );
}
